# Generated by Django 4.0.10 on 2024-04-13 12:07

from django.db import migrations, models
import django.utils.timezone
import django_enumfield.db.fields
import produit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('produit_Id', models.AutoField(primary_key=True, serialize=False)),
                ('code_Produit', models.CharField(max_length=32, unique=True)),
                ('designation', models.CharField(max_length=25)),
                ('date_Creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories_Produit', django_enumfield.db.fields.EnumField(enum=produit.models.Categories)),
            ],
            options={
                'verbose_name': 'produit',
                'db_table': 'produit',
            },
        ),
    ]
