# Generated by Django 4.0.10 on 2024-04-13 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
