# Generated by Django 4.0.10 on 2024-04-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_Miseajour',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=None),
        ),
    ]
